/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as MainStoreRouteImport } from './routes/_main/store'
import { Route as MainProfileRouteImport } from './routes/_main/profile'
import { Route as MainLoginRouteImport } from './routes/_main/login'
import { Route as MainStoreGameIdRouteImport } from './routes/_main/store.$gameId'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const MainStoreRoute = MainStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainStoreGameIdRoute = MainStoreGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => MainStoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof MainLoginRoute
  '/profile': typeof MainProfileRoute
  '/store': typeof MainStoreRouteWithChildren
  '/demo/store': typeof DemoStoreRoute
  '/store/$gameId': typeof MainStoreGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof MainLoginRoute
  '/profile': typeof MainProfileRoute
  '/store': typeof MainStoreRouteWithChildren
  '/demo/store': typeof DemoStoreRoute
  '/store/$gameId': typeof MainStoreGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/login': typeof MainLoginRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/store': typeof MainStoreRouteWithChildren
  '/demo/store': typeof DemoStoreRoute
  '/_main/store/$gameId': typeof MainStoreGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/store'
    | '/demo/store'
    | '/store/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/profile' | '/store' | '/demo/store' | '/store/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/_main/login'
    | '/_main/profile'
    | '/_main/store'
    | '/demo/store'
    | '/_main/store/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  DemoStoreRoute: typeof DemoStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/store': {
      id: '/_main/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof MainStoreRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/store/$gameId': {
      id: '/_main/store/$gameId'
      path: '/$gameId'
      fullPath: '/store/$gameId'
      preLoaderRoute: typeof MainStoreGameIdRouteImport
      parentRoute: typeof MainStoreRoute
    }
  }
}

interface MainStoreRouteChildren {
  MainStoreGameIdRoute: typeof MainStoreGameIdRoute
}

const MainStoreRouteChildren: MainStoreRouteChildren = {
  MainStoreGameIdRoute: MainStoreGameIdRoute,
}

const MainStoreRouteWithChildren = MainStoreRoute._addFileChildren(
  MainStoreRouteChildren,
)

interface MainRouteRouteChildren {
  MainLoginRoute: typeof MainLoginRoute
  MainProfileRoute: typeof MainProfileRoute
  MainStoreRoute: typeof MainStoreRouteWithChildren
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainLoginRoute: MainLoginRoute,
  MainProfileRoute: MainProfileRoute,
  MainStoreRoute: MainStoreRouteWithChildren,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  DemoStoreRoute: DemoStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
